version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} " ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    container_name: migrations
    tty: true
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    build: .
    command: sh -c "cd backend && alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy


  app:
    container_name: app
    tty: true
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    command: ["uvicorn", "backend.src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - '8008:8000'
    depends_on:
      migrations:
        condition: service_completed_successfully


volumes:
  pgdata: